'001':
  url: https://www.fincen.gov/system/files/2026-01/FinCEN-Alert-Federal-Child-Nutrition-Programs.pdf
'002':
  url: https://www.fincen.gov/system/files/shared/FinCEN-Alert-Oil-Smuggling-FINAL-508C.pdf
'003':
  url: https://www.fincen.gov/system/files/shared/BCS-Alert-FINAL-508C.pdf
'004':
  url: https://www.fincen.gov/system/files/2024-12/Alert-FinCEN-Scams-FINAL508.pdf
'005':
  url: https://www.fincen.gov/system/files/shared/FinCEN-Alert-DeepFakes-Alert508FINAL.pdf
'006':
  url: https://www.fincen.gov/system/files/shared/FinCEN-Alert-Hizballah-Alert-508C.pdf
'007':
  url: https://www.fincen.gov/system/files/shared/FinCEN_ERC_Fraud_Alert_FINAL508.pdf
008:
  url: https://www.fincen.gov/system/files/2025-09/FinCEN_Alert_Terrorist_Financing_proof1.pdf
009:
  url: https://www.fincen.gov/system/files/shared/FinCEN_Alert_Pig_Butchering_FINAL_508c.pdf
'010':
  url: https://www.fincen.gov/system/files/shared/FinCEN%20and%20BIS%20Joint%20Alert%20_FINAL_508C.pdf
'011':
  url: https://www.fincen.gov/system/files/shared/FinCEN%20Alert%20Mail%20Theft-Related%20Check%20Fraud%20FINAL%20508.pdf
'012':
  url: https://www.fincen.gov/system/files/shared/FinCEN%20Alert%20Real%20Estate%20FINAL%20508_1-25-23%20FINAL%20FINAL.pdf
'013':
  url: https://www.fincen.gov/system/files/shared/FinCEN%20Alert%20Human%20Smuggling%20FINAL_508.pdf
'014':
  url: https://www.fincen.gov/system/files/2022-06/FinCEN%20and%20Bis%20Joint%20Alert%20FINAL.pdf
'015':
  url: https://www.fincen.gov/system/files/2022-03/FinCEN%20Alert%20Russian%20Elites%20High%20Value%20Assets_508%20FINAL.pdf
'016':
  url: https://www.fincen.gov/system/files/2022-03/FinCEN%20Alert%20Russian%20Sanctions%20Evasion%20FINAL%20508.pdf
'017':
  url: https://www.fincen.gov/system/files/2020-07/FinCEN%20Alert%20Twitter_508%20FINAL.pdf
018:
  url: https://www.fincen.gov/system/files/2026-03/FinCEN-Advisory-Health-Care-Fraud.pdf
019:
  url: https://www.fincen.gov/system/files/2025-08/FinCEN-Advisory-CMLN-508.pdf
'020':
  url: https://www.fincen.gov/system/files/FinCEN-Advisory-Illicit-Oil-Smuggling-508.pdf
'021':
  url: https://www.fincen.gov/system/files/advisory/2025-04-01/FinCEN-Advisory-ISIS-508C.pdf
'022':
  url: https://www.fincen.gov/system/files/advisory/2024-06-20/FinCEN-Supplemental-Advisory-on-Fentanyl-508C.pdf
'023':
  url: https://www.fincen.gov/system/files/advisory/2024-05-07/FinCEN-Advisory-Iran-Backed-TF-508C.pdf
'024':
  url: https://www.fincen.gov/system/files/advisory/2022-06-15/FinCEN%20Advisory%20Elder%20Financial%20Exploitation%20FINAL%20508.pdf
'025':
  url: https://www.fincen.gov/system/files/advisory/2022-04-14/FinCEN%20Advisory%20Corruption%20FINAL%20508.pdf
'026':
  url: https://www.fincen.gov/system/files/advisory/2021-11-08/FinCEN%20Ransomware%20Advisory_FINAL_508_.pdf
'027':
  url: https://www.fincen.gov/system/files/advisory/2021-02-25/Advisory%20EIP%20FINAL%20508.pdf
028:
  url: https://www.fincen.gov/system/files/advisory/2021-02-02/COVID-19%20Health%20Care%20508%20Final.pdf
029:
  url: https://www.fincen.gov/system/files/advisory/2020-10-15/Advisory%20Human%20Trafficking%20508%20FINAL_0.pdf
'030':
  url: https://www.fincen.gov/system/files/advisory/2020-10-13/Advisory%20Unemployment%20Insurance%20COVID%2019%20508%20Final.pdf
'031':
  url: https://www.fincen.gov/system/files/advisory/2020-07-30/FinCEN%20Advisory%20Covid%20Cybercrime%20508%20FINAL.pdf
'032':
  url: https://www.fincen.gov/system/files/advisory/2020-05-18/Advisory%20Medical%20Fraud%20Covid%2019%20FINAL%20508.pdf
'033':
  url: https://www.fincen.gov/system/files/2025-09/FinCEN-Notice-FMS-508C.pdf
'034':
  url: https://www.fincen.gov/system/files/2025-08/FinCEN-Notice-CVCKIOSK.pdf
'035':
  url: https://www.fincen.gov/system/files/shared/FinCEN-Joint-Notice-Timeshare-Mexico-508C-FINAL.pdf
'036':
  url: https://www.fincen.gov/system/files/shared/FinCEN_Notice_Counterfeit_US_Passport_FINAL508.pdf
'037':
  url: https://www.fincen.gov/system/files/shared/FinCEN_Joint_Notice_US_Export_Controls_FINAL508.pdf
038:
  url: https://www.fincen.gov/system/files/2025-09/FinCEN_Notice_Payroll_Tax_Evasion_and_Workers_Comp_508.pdf
039:
  url: https://ofac.treasury.gov/media/935441/download?inline
'041':
  url: https://ofac.treasury.gov/media/912981/download?inline
'042':
  url: https://ofac.treasury.gov/media/913571/download?inline
'043':
  url: https://ofac.treasury.gov/media/932166/download?inline
'044':
  url: https://ofac.treasury.gov/media/932436/download
'045':
  url: https://home.treasury.gov/system/files/136/REPO_Joint_Advisory.pdf
'046':
  url: https://ofac.treasury.gov/media/932336/download
'047':
  url: https://ofac.treasury.gov/media/931996/download
048:
  url: https://ofac.treasury.gov/media/16331/download?inline
049:
  url: https://ofac.treasury.gov/media/7726/download?inline=
'050':
  url: https://ofac.treasury.gov/media/16506/download?inline=
'051':
  url: https://ofac.treasury.gov/media/36061/download
'052':
  url: https://ofac.treasury.gov/system/files/126/20220516_dprk_it_worker_advisory.pdf
'053':
  url: https://ofac.treasury.gov/media/37751/download?inline=
'054':
  url: https://bsaaml.ffiec.gov/manual/Appendices/07
'055':
  url: https://bsaaml.ffiec.gov/manual
'056':
  url: https://ofac.treasury.gov/media/923126/download?inline
'057':
  url: https://www.ic3.gov/AnnualReport/Reports/2024_IC3Report.pdf
058:
  url: https://www.ic3.gov/Media/PDF/AnnualReport/2023_IC3Report.pdf
059:
  url: https://www.finra.org/rules-guidance/notices/19-18
'060':
  url: https://www.irs.gov/pub/irs-pdf/p3583.pdf
'061':
  url: https://fintrac-canafe.canada.ca/guidance-directives/transaction-operation/indicators-indicateurs/fin_mltf-eng
'062':
  url: https://fintrac-canafe.canada.ca/guidance-directives/transaction-operation/indicators-indicateurs/msb_mltf-eng
'063':
  url: https://fintrac-canafe.canada.ca/guidance-directives/transaction-operation/indicators-indicateurs/real_mltf-eng
'064':
  url: https://fintrac-canafe.canada.ca/guidance-directives/transaction-operation/indicators-indicateurs/vc_mltf-eng
'067':
  url: https://fintrac-canafe.canada.ca/intel/operation/exploitation-eng
068:
  url: https://fintrac-canafe.canada.ca/intel/operation/oai-hts-2021-eng
069:
  url: https://fintrac-canafe.canada.ca/intel/operation/ml-rec-eng
'070':
  url: https://fintrac-canafe.canada.ca/intel/operation/oai-ml-eng
'077':
  url: https://www.handbook.fca.org.uk/handbook/FCG.pdf
078:
  url: https://www.handbook.fca.org.uk/handbook/FCTR.pdf
079:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/635-sars-glossary-codes-and-reporting-routes/file
080:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/749-sars-in-action-issue-31/file
081:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/714-sars-reporter-booklet-april-2024-v0-3/file
082:
  url: https://www.nationalcrimeagency.gov.uk/images/campaign/NSA/PDFs/NSA%202025%20Website%20-%20PDF%20Version%20v1.0.pdf
083:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/605-necc-financial-sanctions-evasion-russian-elites-and-enablers/file
084:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/769-necc-amber-alert-networks-and-shadow-fleets/file
085:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/516-necc-art-market-participants-aml-regulations-and-financial-crime-vulnerabilities/file
086:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/334-nca-amber-alert-online-sale-of-fentanyl-analogues/file
087:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/486-necc-bribery-corruption-risks-to-uk-independent-schools-alert/file
088:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/580-necc-payment-division-fraud-amber-alert/file
089:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/687-necc-red-alert-exporting-high-risk-goods/file
090:
  url: https://www.nationalcrimeagency.gov.uk/who-we-are/publications/679-necc-red-alert-gold-sanctions-circumvention/file
091:
  url: https://assets.publishing.service.gov.uk/media/67f3f2467ed82b90fcf5bffc/OFSI_Financial_Services_Threat_Assessment_Report.pdf
092:
  url: https://assets.publishing.service.gov.uk/media/6835e2f4214f7f554cf6932a/OFSI_Legal_Services_Threat_Assessment.pdf
093:
  url: https://www.gov.uk/government/publications/sanctions-compliance-in-the-cryptoassets-sector-threat-assessment
095:
  url: https://assets.publishing.service.gov.uk/media/5cdd76ebe5274a774d84148a/Anti-money_laundering__compliance_in_the_MSB_sector.pdf
096:
  url: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/348648/Money-laundering-guidance-for-money-service-businesses.pdf
098:
  url: https://www.eba.europa.eu/sites/default/files/document_library/Publications/Guidelines/2023/1054143/Amending%20GLs%20to%20the%20RFGLs%20in%20relation%20to%20NPOs.pdf
099:
  url: https://www.eba.europa.eu/sites/default/files/document_library/Publications/Guidelines/2023/1054144/Guidelines%20on%20MLTF%20risk%20management%20and%20access%20to%20financial%20services.pdf
'100':
  url: https://www.eba.europa.eu/sites/default/files/2024-01/a3e89f4f-fbf3-4bd6-9e07-35f3243555b3/Final%20Amending%20%20Guidelines%20on%20MLTF%20Risk%20Factors.pdf
'103':
  url: https://www.europol.europa.eu/publication-events/main-reports/internet-organised-crime-threat-assessment-iocta-2025
'106':
  url: https://www.afm.nl/~/profmedia/files/wet-regelgeving/beleidsuitingen/leidraden/guidelines-wwft-sw.pdf
'107':
  url: https://www.afm.nl/~/profmedia/files/wet-regelgeving/2025/annex-guideline-wwft-sanctions.pdf
'114':
  url: https://www.cssf.lu/en/Document/circular-cssf-18-698/
'120':
  url: https://www.coe.int/en/web/moneyval/activities/typologies
'121':
  url: https://www.mas.gov.sg/regulation/notices/notice-626
'122':
  url: https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulatory-and-Supervisory-Framework/Anti_Money-Laundering_Countering-the-Financing-of-Terrorism/Guidance-for-Effective-AML-CFT-Transaction-Monitoring-Controls.pdf
'123':
  url: https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulatory-and-Supervisory-Framework/Anti_Money-Laundering_Countering-the-Financing-of-Terrorism/Guidance-to-Capital-Markets-Intermediaries-on-Enhancing-AMLCFT-Frameworks-and-Controls.pdf
'124':
  url: https://www.mas.gov.sg/-/media/MAS/News-and-Publications/Monographs-and-Information-Papers/Guidance-on-AML-CFT-Controls-in-Trade-Finance-and-Correspondent-Banking.pdf
'125':
  url: https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulations-Guidance-and-Licensing/Payment-Service-Providers/Strengthening-AMLCFT-Controls-of-Digital-Payment-Token-Service-Providers.pdf
'126':
  url: https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulatory-and-Supervisory-Framework/Anti_Money-Laundering_Countering-the-Financing-of-Terrorism/Effective-Practices-to-Detect-and-Mitigate-the-Risk-from-Misuse-of-Legal-Persons-June-2019.pdf
'127':
  url: https://www.mas.gov.sg/regulation/guidance/amlcft-controls-on-risks-of-misuse-of-legal-persons-arrangements-and-complex-structures
'128':
  url: https://abs.org.sg/docs/library/legal-persons-misuse-typologies-and-best-practice.pdf
'129':
  url: https://www.mas.gov.sg/regulation/anti-money-laundering/amlcft-industry-partnership-acip
'130':
  url: https://www.mas.gov.sg/regulation/anti-money-laundering/ml-tf-pf-risk-assessments
'131':
  url: https://www.hkma.gov.hk/media/eng/doc/key-information/guidelines-and-circular/guideline/Guideline_on_AML-CFT_(for_SVFs)_eng_May%202023.pdf
'132':
  url: https://www.hkma.gov.hk/media/eng/doc/key-information/guidelines-and-circular/2023/20230209e2a2.pdf
'133':
  url: https://www.sfc.hk/-/media/EN/assets/components/codes/files-current/web/guidelines/guideline-on-anti-money-laundering-and-counter-financing-of-terrorism-for-licensed-corporations/AML-Guideline-for-LCs_Eng_30-Sep-2021.pdf
'134':
  url: https://www.jfiu.gov.hk/en/str_main.html
'135':
  url: https://www.drs.customs.gov.hk/download/drsguideline/AML_CFT_Guideline_en.pdf
'136':
  url: https://www.npa.go.jp/sosikihanzai/jafic/en/nenzihokoku_e/data/jafic_e2024.pdf
'137':
  url: https://www.npa.go.jp/sosikihanzai/jafic/en/nenzihokoku_e/data/jafic_e2023.pdf
'139':
  url: https://www.kofiu.go.kr/eng/main.do
'141':
  url: https://fiuindia.gov.in/pdfs/downloads/AnnualReport2021_22.pdf
'142':
  url: https://fiuindia.gov.in/pdfs/quicklinks/User_Manual_VASP.pdf
'143':
  url: https://www.rbi.org.in/Scripts/BS_ViewMasterDirections.aspx?id=11566
'147':
  url: https://www.ppatk.go.id/backend/assets/images/publikasi/1658219051_.pdf
'148':
  url: https://www.amlo.go.th/amlo-intranet/media/k2/attachments/NRAYThailandYforYPublicationYEnglish_6112.pdf
'149':
  url: http://www.amlc.gov.ph/images/PDFs/PR2023/2022%20DEC%20TYPOLOGIES%20BRIEF%20MONEY%20MULES_For%20Publication.pdf
'150':
  url: http://www.amlc.gov.ph/images/PDFs/Main/2022%20TERRORISM%20AND%20TF%20STUDY%20-%20Executive%20Summary%20(WEBSITE).pdf
'151':
  url: http://www.amlc.gov.ph/images/PDFs/2021-AMLC%20REGISTRATION%20AND%20REPORTING%20GUIDELINES.pdf
'152':
  url: http://www.amlc.gov.ph/home/16-news-and-announcements/236-advisory-on-the-typologies-report-on-the-use-of-filipinos-and-businesses-as-dummies
'153':
  url: https://www.mjib.gov.tw/userfiles/files/35-%E6%B4%97%E9%8C%A2%E9%98%B2%E5%88%B6%E8%99%95/files/%E6%B4%97%E9%8C%A2%E9%98%B2%E5%88%B6%E8%99%95-EN/2021%20NRA%20Report.pdf
'154':
  url: https://rulebook.centralbank.ae/en/rulebook/amlcft
'155':
  url: https://rulebook.centralbank.ae/en/rulebook/annex-1-tbml-and-illicit-transshipment-red-flags
'156':
  url: https://rulebook.centralbank.ae/en/rulebook/guidance-licensed-financial-institutions-implementation-targeted-financial-sanctions
'157':
  url: https://www.centralbank.ae/media/tdikym4m/amlcft-guidance-for-licensed-financial-institutions-providing-services-to-legal-persons-and-arrangements.pdf
'158':
  url: https://rulebook.centralbank.ae/en/rulebook/guidance-licensed-financial-institutions-suspicious-transaction-reporting
'160':
  url: https://assets.adgm.com/download/assets/Anti-Money+Laundering+and+Sanctions+Rules+and+Guidance+AML+20250210.pdf/6a0053227a6911ef819fe625b52cf370
'161':
  url: https://www.sama.gov.sa/en-US/RulesInstructions/AML%20Rules/Money%20Laundering.pdf
'162':
  url: https://www.sama.gov.sa/en-US/Laws/BankingRules/Anti-Money%20Laundering%20and%20Counter-Terrorist%20Financing%20Rules.pdf
'164':
  url: https://www.austrac.gov.au/business/how-comply-and-report-guidance-and-resources/guidance-resources/risk-assessments
'166':
  url: https://www.austrac.gov.au/industry-and-business/education-and-resources/publications-and-resources/indicators-suspicious-activity-banking-sector
'167':
  url: https://www.austrac.gov.au/industry-and-business/education-and-resources/publications-and-resources/indicators-suspicious-activity-securities-and-derivatives-sector
'175':
  url: https://www.austrac.gov.au/industry-and-business/education-and-resources/publications-and-resources/typologies-paper-austrac-money-laundering-and-terrorism-financing-indicators
'180':
  url: https://www.fatf-gafi.org/en/publications/Methodsandtrends/Trade-based-money-laundering-trends-and-developments.html
'184':
  url: https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Guidance-rba-real-estate-sector.html
'190':
  url: https://fiaumalta.org/app/uploads/2025/03/March-2025-Detecting-Disrupting-and-Investigating-Online-Child-Sexual-Exploitation.pdf
'191':
  url: https://www.fatf-gafi.org/en/publications/Financingofproliferation/complex-proliferation-financing-sanction-evasion-schemes.html
'193':
  url: https://www.fatf-gafi.org/en/publications/Methodsandtrends/Concealment-beneficial-ownership.html
'195':
  url: https://www.fatf-gafi.org/en/publications/Financingofproliferation/Guidance-counter-proliferation-financing.html
'196':
  url: https://www.fatf-gafi.org/en/publications/Methodsandtrends/Moneylaunderingandterroristfinancingthroughtherealestatesector.html
'197':
  url: https://www.fatf-gafi.org/en/publications/Methodsandtrends/Trade-basedmoneylaundering.html
'200':
  url: https://www.gleif.org/lei-solutions/featuring-the-lei/cross-border-payments/wolfsberg-group-payment-transparency-standards-2023.pdf
'203':
  url: https://library.iccwbo.org/content/tfb/pdf/trade-finance-principles-2019-amendments-wolfsberg-icc-baft-final.pdf
'204':
  url: https://www.bis.org/bcbs/publ/d505.htm
'205':
  url: https://ofac.treasury.gov/media/934236/download?inline
'206':
  url: https://www.fincen.gov/system/files/2026-05/FinCEN-WCHT-Notice.pdf
'207':
  url: https://www.fincen.gov/system/files/2026-05/FinCEN-Alert-IRGC.pdf
