#!/usr/bin/env python3
"""Regenerate red_flag_sources/sources.yaml from red_flag_sources/pdflinks.txt.

Usage:
    uv run python scripts/build_sources_registry.py

Each non-blank, non-comment line in pdflinks.txt becomes one entry:
  line 1 → key "001", line 2 → "002", etc.

Fully overwrites sources.yaml. Edit pdflinks.txt and re-run to update.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PDFLINKS_PATH = PROJECT_ROOT / "red_flag_sources" / "pdflinks.txt"
SOURCES_REGISTRY_PATH = PROJECT_ROOT / "red_flag_sources" / "sources.yaml"

HEADER = (
    "# Source URL registry — generated by scripts/build_sources_registry.py\n"
    "# Edit red_flag_sources/pdflinks.txt and re-run to update.\n"
    "# Maps serial key (matching PDF filename prefix NNN_...) to public URL.\n\n"
)


def main() -> None:
    if not PDFLINKS_PATH.exists():
        print(f"Error: {PDFLINKS_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    urls: list[str] = []
    with open(PDFLINKS_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            urls.append(line)

    if not urls:
        print("No URLs found in pdflinks.txt — sources.yaml not modified.")
        sys.exit(0)

    registry = {f"{i + 1:03d}": {"url": url} for i, url in enumerate(urls)}

    with open(SOURCES_REGISTRY_PATH, "w") as f:
        f.write(HEADER)
        yaml.dump(registry, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

    print(f"Written {len(registry)} entries to {SOURCES_REGISTRY_PATH.relative_to(PROJECT_ROOT)}")
    for key, entry in sorted(registry.items()):
        print(f"  {key}: {entry['url']}")


if __name__ == "__main__":
    main()
